name: Tests

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Run go mod
        run: make go.sum

      - name: Run make test
        run: make test
